# Generated by Django 5.0.4 on 2024-05-03 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('editorialName', models.CharField(max_length=200)),
                ('autorName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('dateReturn', models.DateField(default=datetime.date.today, verbose_name='Date Return')),
            ],
        ),
        migrations.CreateModel(
            name='Prestatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=200)),
            ],
        ),
    ]
