# Generated by Django 5.0.4 on 2024-05-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamolibro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestatario'),
        ),
        migrations.AlterField(
            model_name='prestamolibro',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro'),
        ),
    ]
